# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('destruction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('clan_tag', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('war_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=3000)),
                ('type', models.CharField(choices=[('comment', 'comment'), ('review', 'review')], default='comment', max_length=300)),
                ('time', models.DateTimeField(auto_now=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='war_room_app.Base')),
            ],
        ),
        migrations.CreateModel(
            name='Dib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True, default=0, null=True)),
                ('destruction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='war_room_app.Base')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('game_name', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='./static/photos')),
                ('total_stars', models.IntegerField(blank=True, default=0)),
                ('clan_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='war_room_app.Clan')),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('clan_tag', models.CharField(max_length=45)),
                ('enemy_clan_tag', models.CharField(max_length=45)),
                ('stars', models.IntegerField(blank=True, default=0)),
                ('enemy_stars', models.IntegerField(blank=True, default=0)),
                ('destruction', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('enemy_destruction', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='war_room_app.Clan')),
            ],
        ),
        migrations.AddField(
            model_name='dib',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='war_room_app.Member'),
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='war_room_app.Member'),
        ),
        migrations.AddField(
            model_name='base',
            name='war',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='war_room_app.War'),
        ),
    ]
