# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('war_room_app', '0002_auto_20160219_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='war',
            name='clan',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='war_room_app.Clan'),
        ),
    ]
