# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_room_app', '0003_auto_20160219_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='war',
            name='size',
            field=models.IntegerField(choices=[(15, '10 Vs 10'), (15, '15 Vs 15'), (15, '20 Vs 20'), (15, '25 Vs 25'), (15, '30 Vs 30'), (15, '35 Vs 35'), (15, '40 Vs 40'), (15, '45 Vs 45'), (15, '50 Vs 50')], default=10),
        ),
    ]
