# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_room_app', '0008_auto_20160305_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
